'use client';
import NavBar from '../components/NavBar';
import Todo from './ToDo'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        
      <div >

      <NavBar/>
      <Todo/>
      {/* <body className={inter.className}>{children}</body> */}
    </div>
      </body>
    </html>
    
  )
}
